models/Batafsil.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "batafsil".
 *
 * @property int $id
 * @property int $davolanish_id
 * @property int $davo_id
 * @property int $narxi
 * @property string $description
 *
 * @property Davolanish $davolanish
 * @property Davo $davo
 */
class Batafsil extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'batafsil';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['davo_id', 'narxi'], 'required'],
            [['davolanish_id', 'davo_id', 'narxi'], 'integer'],
            [['description'], 'string'],
            [['davolanish_id'], 'exist', 'skipOnError' => true, 'targetClass' => Davolanish::className(), 'targetAttribute' => ['davolanish_id' => 'id']],
            [['davo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Davo::className(), 'targetAttribute' => ['davo_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'davolanish_id' => 'Бемор Ф.И.Ш.',
            'davo_id' => 'Касаллик тури',
            'narxi' => 'Нархи',
            'description' => 'Маълумот',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDavolanish()
    {
        return $this->hasOne(Davolanish::className(), ['id' => 'davolanish_id']);
    }
    public function getBemor()
    {
        return $this->hasOne(Bemor::className(), ['id' => 'bemor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDavo()
    {
        return $this->hasOne(Davo::className(), ['id' => 'davo_id']);
    }
}

controllers/Batafsil2Controller.php
<?php

namespace app\controllers;

use app\models\Davolanish;
use yii\filters\AccessControl;
use Yii;
use app\models\Batafsil;
use app\models\BatafsilSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BatafsilController implements the CRUD actions for Batafsil model.
 */
class BatafsilController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
//                'only' => ['logout'],
                'rules' => [
                    [
//                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Batafsil models.
     * @return mixed
     */
    public function actionIndex($davolanish_id)
    {
        $searchModel = new BatafsilSearch();

        $params = Yii::$app->request->queryParams;
        $params['BatafsilSearch']['davolanish_id'] = $davolanish_id;
        $dataProvider = $searchModel->search($params);

        $davolanish = Davolanish::findOne($davolanish_id);
        //$davolanish = Davolanish::find()->where(['id'=>$davolanish_id])->one();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'davolanish' => $davolanish,
        ]);
    }

    /**
     * Displays a single Batafsil model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Batafsil model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($davolanish_id)
    {
        $model = new Batafsil();
        $davolanish = Davolanish::findOne($davolanish_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'davolanish' => $davolanish,
        ]);
    }

    /**
     * Updates an existing Batafsil model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $davolanish = Davolanish::findOne($davolanish_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Batafsil model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $davolanish = $model->davolanish_id;

        $this->findModel($id)->delete();

        return $this->redirect(['index', 'davolanish_id'=>$davolanish]);
    }

    /**
     * Finds the Batafsil model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Batafsil the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Batafsil::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/batafsil2/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Batafsil */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="batafsil-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= Html::activeHiddenInput($model, 'davolanish_id', ['value' => $davolanish_id])  ?>

    <?= $form->field($model, 'davo_id')->dropDownList(\app\models\Davo::all()) ?>

    <?= $form->field($model, 'narxi')->textInput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/batafsil2/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BatafsilSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="batafsil-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'davolanish_id') ?>

    <?= $form->field($model, 'davo_id') ?>

    <?= $form->field($model, 'narxi') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/batafsil2/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Batafsil */

$davolanish_id = $davolanish->id;

$this->title = 'Батафсил қўшиш';
$this->params['breadcrumbs'][] = ['label' => 'Даволаниш', 'url' => ['/../davolanish']];
$this->params['breadcrumbs'][] = ['label' => 'Батафсил', 'url' => ['index?davolanish_id='.$davolanish_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="batafsil-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'davolanish_id'=>$davolanish->id
    ]) ?>

</div>

views/batafsil2/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BatafsilSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Батафсил';
$this->params['breadcrumbs'][] = ['label' => 'Даволаниш', 'url' => ['/../davolanish']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="batafsil-index">

    <?php $davolanish->date = date("d.m.Y"); ?>
    <h3><?= $davolanish->bemor->fio .' / '. $davolanish->date.' / '.$davolanish->came_from ;
    ?></h3>

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Даволанганни қўшиш', ['create', 'davolanish_id' => $davolanish->id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'davo_id',
                'value' => function($model){
                return $model->davo->name;
            }
            ],
            [
                'attribute' => 'narxi',
                'format' => ['decimal', 0],
                'contentOptions' => ['style'=>'text-align:right'],
            ],
            'description:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/batafsil2/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Batafsil */


$this->title = 'Батафсил тахрирлаш: '.$model->davolanish->bemor->fio;
$this->params['breadcrumbs'][] = ['label' => 'Батафсил', 'url' => ['index', 'davolanish_id' => $model->davolanish_id]];
$this->params['breadcrumbs'][] = ['label' => $model->davolanish->bemor->fio, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Тахрирлаш';
?>
<div class="batafsil-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'davolanish_id' =>$davolanish->id,
    ]) ?>

</div>

views/batafsil2/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Batafsil */

$this->title = $model->davolanish->bemor->fio;
$this->params['breadcrumbs'][] = ['label' => 'Даволаниш', 'url' => ['/../davolanish']];
$this->params['breadcrumbs'][] = ['label' => 'Батафсил', 'url' => ['index', 'davolanish_id'=>$model->davolanish_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="batafsil-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Тахрирлаш', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Ўчириш', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Ўчиришга ишончингиз комилми?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'davolanish_id',
                'value' => function($model){
                    return $model->davolanish->bemor->fio;
                }
            ],
            [
                'attribute' => 'davo_id',
                'value' => function($model){
                    return $model->davo->name;
                }
            ],
            'narxi',
            'description:ntext',
        ],
    ]) ?>

</div>